[package]
name = "anawt"
version = "0.1.0"
edition = "2024"
description = "All names were taken"
repository = "https://github.com/pliduino/anawt"

[dependencies]
lt-rs = { git = "https://github.com/pliduino/lt-rs.git", branch = "develop" }
lt-rs = { path = "../lt-rs" }

rclite = "0.3.0"
tokio = { version = "1.47.1", features = [
    "sync",
    "rt-multi-thread",
    "macros",
    "net",
] }
tracing = "0.1.41"

[features]
default = []
lto = ["lt-rs/lto"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
